site_name: Servidor LGBIO
site_url: https://example.com
theme:
  name: material
  language: pt-BR
  #logo: assets/logo.png
  #favicon: assets/favicon.png

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom        # <- uses colors from docs/stylesheets/extra.css
      accent: custom
      toggle:
        icon: material/brightness-7
        name: change to dim mode
    # Dim mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: change to light mode

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - navigation.footer
    - search.highlight
    - search.suggest
    - search.share
    - content.code.copy
    - content.tabs.link
    - toc.follow

  #icon:
   # repo: fontawesome/brands/github

# Carrega o CSS personalizado
extra_css:
  - stylesheets/extra.css