site_name: SERVIDOR LGBIO
site_description: Documentação do Servidor LGBIO
#site_url: 
#repo_url:
#repo_name:
edit_uri: edit/main/docs/
use_directory_urls: false

theme:
  name: material
  language: pt-BR
  #logo:
  #favicon:

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Light mode
      primary: custom
      accent: custom

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Dark mode
      primary: custom
      accent: custom

  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.top
  - navigation.indexes
  - navigation.footer
  - search.highlight
  - search.suggest
  - search.share
  - content.code.copy
  - content.tabs.link
  - toc.follow

  icon:
    repo: fontawesome/brands/github

# load custom CSS
extra_css:
  - stylesheets/extra.css
