site_name: Servidor LGBIO
site_url: https://example.com
theme:
  name: material
  language: pt-BR
  #logo: assets/logo.png
  #favicon: assets/favicon.png

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom        # <- uses colors from docs/stylesheets/extra.css
      accent: custom
      toggle:
        icon: material/brightness-7
        name: change to dim mode
    # Dim mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: change to light mode

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - navigation.footer
    - search.highlight
    - search.suggest
    - search.share
    - content.code.copy
    - content.tabs.link
    - toc.integrate # remove the "Table of contents" title and make the TOC sticky

  #icon:
   # repo: fontawesome/brands/github

# Carrega o CSS personalizado
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  # Caixinhas (admonitions) e dobráveis
  - admonition
  - pymdownx.details

  # Blocos de código (com botão de copiar, syntax highlight)
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite

  # Abas
  - pymdownx.tabbed:
      alternate_style: true

  # Listas de tarefas com checkbox
  - pymdownx.tasklist:
      custom_checkbox: true

  # Ícones do Material via :material-nome:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - attr_list
  - md_in_html
  - tables
  - footnotes
  - def_list
  - toc:
      permalink: true

nav:
  - Início: index.md
  - Contato: contato/index.md